// Original prototype content. Legal rules are hypothetical, not statements of law.
globalThis.CLATPracticeSets = [
 {id:'english-01',section:'English Language',icon:'book-open',title:'When a shortcut becomes a habit',topic:'Inference · Tone · Main idea',reading:true,paragraphs:[
 'A school introduced automatic summaries alongside its digital reading materials. Students welcomed the change: a page of difficult prose could now become a handful of clear sentences. Teachers also found a use for the summaries, especially when introducing unfamiliar subjects. Yet a tool that made entry easier could also make sustained reading seem unnecessary. Some students began consulting the summary before deciding whether the original was worth their attention.',
 'The concern was not simply that summaries left things out. Every useful summary must select. The difficulty was that the selection arrived already made, hiding the choices that a reader would otherwise have to consider. A qualification might disappear, an example might become a conclusion, or two competing explanations might be compressed into one. A student could remember the central claim while missing how cautiously the author had advanced it.',
 'One teacher therefore changed the sequence. Students first read the original and wrote a brief account of its argument. Only then did they compare their accounts with the automatic version. Disagreements became a reason to return to the text: which phrase justified a stronger claim, and which detail changed its meaning? The summary became an object of examination rather than the final authority.',
 'This approach did not require rejecting the technology. It required deciding what work the technology should do. Saving time is valuable, but education also involves learning which judgments deserve time. A shortcut can support that learning when it reveals a difficult choice. It can weaken it when the choice disappears from view.'
 ],questions:[
 ['What is the central argument?',['Automatic summaries should be banned.','Summaries are useful when they support a reader’s own judgment.','Students should always read summaries first.','Shorter texts are more accurate.'],1,'The author supports examining summaries after independent reading, so that the tool supports judgment rather than replacing it.'],
 ['Why does the teacher change the sequence?',['To prevent students from using technology at all.','To ensure every student writes identical summaries.','To let students form an interpretation before comparing it with the tool.','To remove the need to revisit the original.'],2,'Students first write their own account. Comparing it afterwards makes the tool’s selection open to examination.'],
 ['What does “qualification” mean here?',['A professional certificate','A limit or condition attached to a claim','An entrance requirement','A supporting illustration'],1,'The surrounding discussion concerns how cautiously a claim is made. A qualification narrows or limits that claim.'],
 ['Which inference is best supported?',['Remembering a conclusion does not necessarily mean understanding its reasoning.','All automatic summaries distort every text.','Teachers find summaries useless.','Independent reading removes every ambiguity.'],0,'The second paragraph distinguishes remembering the central claim from noticing how cautiously the author advances it.'],
 ['Which description best fits the tone?',['Hostile and mocking','Unreservedly enthusiastic','Reflective and cautiously constructive','Indifferent to learning'],2,'The author acknowledges benefits, identifies a risk, and proposes a constructive way to use the tool.']
 ]},
 {id:'gk-01',section:'Current Affairs & GK',icon:'globe',title:'Climate and the natural world',topic:'General knowledge · Environment',reading:false,paragraphs:[
 'A student newspaper is preparing an environment issue. Its editors want to distinguish weather from climate, explain why different energy sources matter, and connect ecosystem protection with everyday decisions. The questions below check general knowledge related to that theme. Some answers require knowledge beyond this short introduction.'
 ],questions:[
 ['Which best describes climate?',['The temperature at noon on one day','Long-term patterns of weather in a region','A single severe storm','Tomorrow’s rain forecast'],1,'Climate describes long-term weather patterns. A day’s temperature or a particular storm is weather.'],
 ['Which gas is absorbed by plants during photosynthesis?',['Oxygen','Helium','Carbon dioxide','Neon'],2,'Plants use carbon dioxide and water, with light energy, to produce sugars through photosynthesis.'],
 ['Which is a renewable energy source?',['Coal','Petroleum','Natural gas','Wind'],3,'Wind is naturally replenished. Coal, petroleum and natural gas are fossil fuels formed over very long periods.'],
 ['Biodiversity refers to which of the following?',['Only the number of trees in a park','The variety of life, including genetic, species and ecosystem diversity','Only animals that live on land','The amount of rain received by a forest'],1,'Biodiversity includes variation within species, between species, and across ecosystems. It is broader than a count of trees or land animals.'],
 ['Which action directly reduces the amount of waste requiring disposal?',['Using a refillable bottle repeatedly','Replacing a usable bottle every day','Mixing batteries with food scraps','Buying individually wrapped portions when bulk alternatives are suitable'],0,'Repeated use avoids some new disposable packaging. The other choices increase waste or make handling it harder.']
 ]},
 {id:'legal-01',section:'Legal Reasoning',icon:'scale',title:'A promise to hold a book',topic:'Apply a rule · Exceptions',reading:false,paragraphs:[
 'Apply only the following hypothetical rules. A community library must hold a reserved book until 6 pm on the collection date. After that time it may offer the book to the next person. If the library receives an extension request before 6 pm, the reservation automatically continues until noon the next day. Only one extension is allowed. A request received exactly at 6 pm is not received before 6 pm.',
 'If the library is closed for the whole collection date, the original collection deadline moves to 6 pm on its next open day. A partial-day closure does not change the deadline. A valid extension takes priority over a waiting person’s request. These rules are invented for this exercise; do not assume any additional legal principles.'
 ],questions:[
 ['Mira’s collection deadline is Monday at 6 pm. Her first extension request arrives at 5:55 pm. When does her reservation expire?',['Monday at 6 pm','Tuesday at noon','Tuesday at 6 pm','Wednesday at noon'],1,'A first request received before 6 pm automatically extends the reservation until noon the next day.'],
 ['Arun’s first request arrives exactly at 6 pm on his collection date. Which follows?',['An extension is automatic.','The book must be held until midnight.','The library may offer it to the next person after 6 pm.','The reservation lasts another week.'],2,'The rule expressly excludes a request received exactly at 6 pm. The original deadline therefore applies.'],
 ['The library is closed all Tuesday, Dev’s collection date. It next opens Thursday. What is the original deadline now?',['Wednesday at noon','Thursday at 6 pm','Thursday at noon','Friday at 6 pm'],1,'A whole-day closure moves the original deadline to 6 pm on the next open day, which is Thursday.'],
 ['Leena already received an extension until Friday noon. At 11 am Friday she asks for another. Must the library extend again?',['Yes, because she asked before noon.','Yes, because requests always take priority.','No, because only one extension is allowed.','No, because extensions must be requested in person.'],2,'Only one extension is allowed. The rules say nothing about requiring an in-person request.'],
 ['On Ali’s collection date the library closes from 1 pm to 3 pm. No extension is requested. When is the deadline?',['3 pm that day','Noon the next day','6 pm on the next open day','6 pm that day'],3,'A partial-day closure does not change the original 6 pm deadline.']
 ]},
 {id:'logical-01',section:'Logical Reasoning',icon:'brain',title:'Does a reminder change behaviour?',topic:'Causation · Assumptions · Evidence',reading:true,paragraphs:[
 'A college sent text reminders to students with overdue books. In the following month, late returns fell sharply. The librarian concluded that the reminders had changed students’ habits and proposed sending them throughout the year. The conclusion sounded plausible: a timely message could prompt someone to act on an intention they had forgotten.',
 'A colleague pointed out that the same month also brought a temporary waiver of late fees. Students who had avoided returning a book because they feared a large bill now had a reason to bring it back. In addition, the term was ending, and many students were preparing to leave campus. Either change might have affected the return figures even without reminders.',
 'The colleague suggested a further test. Students with comparable borrowing histories could be randomly assigned to receive a reminder or no reminder, while fee rules and collection dates remained the same for both groups. Researchers would compare the proportion of books returned by the deadline, rather than just the total number. This would help account for differences in group size.',
 'Even a clear advantage for the reminder group would answer a narrower question than the librarian first claimed. It would show an effect under the conditions tested. It would not establish that students had developed a lasting habit, or that more frequent messages would produce a larger benefit. Those claims would require additional evidence over time.'
 ],questions:[
 ['What is the main weakness in the librarian’s initial reasoning?',['It considers an outcome that cannot be counted.','It attributes a change to reminders despite other simultaneous changes.','It proves that fee waivers never work.','It assumes students cannot receive messages.'],1,'The fee waiver and end of term provide alternative explanations for the fall in late returns.'],
 ['What is the purpose of keeping fee rules the same in both groups?',['To remove one competing explanation for a difference in returns','To guarantee that every student returns a book','To make reminders compulsory for everyone','To prove that fees are unfair'],0,'Holding fee rules constant helps isolate the effect of the reminders from the effect of different fees.'],
 ['Why compare proportions rather than totals?',['Proportions remove every source of bias.','Totals cannot be recorded.','Groups may contain different numbers of books or borrowers.','Proportions prove lasting habits.'],2,'A larger group may return more books simply because it is larger. Proportions allow a more meaningful comparison.'],
 ['Which finding would best support a lasting change in habits?',['Students return more books only during the fee waiver.','Many students say they liked the message.','The college sends twice as many messages.','Improved on-time returns persist over later terms after reminders stop, relative to a comparable group.'],3,'Persistence after reminders stop, against a comparison, is relevant evidence for a durable change rather than a short-term prompt.'],
 ['If the proposed test favours reminders, which conclusion is most justified?',['Frequent messages always improve behaviour.','Reminders helped under the tested conditions.','Fee waivers have no effect anywhere.','Every student formed a permanent habit.'],1,'The final paragraph limits the conclusion to the conditions tested; permanence and greater frequency need further evidence.']
 ]},
 {id:'quant-01',section:'Quantitative Techniques',icon:'calculator',title:'A reading club’s numbers',topic:'Percentages · Ratios · Averages',reading:false,paragraphs:[
 'A reading club records new memberships over four months. January: 120; February: 150; March: 180; April: 150. Each new member pays a one-time joining fee of ₹200. In March, 40% of new members choose the fiction group and the rest choose the non-fiction group. Use only these figures; assume there are no discounts or refunds.'
 ],questions:[
 ['What is the percentage increase in new memberships from January to February?',['20%','25%','30%','125%'],1,'The increase is 150 − 120 = 30. Relative to January, 30 ÷ 120 × 100 = 25%.'],
 ['What is the ratio of new memberships in March to April, in simplest form?',['5 : 6','3 : 2','6 : 5','4 : 5'],2,'180 : 150 simplifies to 6 : 5 after dividing both quantities by 30.'],
 ['How many new March members choose non-fiction?',['72','90','108','120'],2,'Non-fiction accounts for 100% − 40% = 60%. Thus 180 × 0.60 = 108 members.'],
 ['What is the average number of new memberships per month?',['140','145','150','160'],2,'The total is 120 + 150 + 180 + 150 = 600. Dividing by four months gives 150.'],
 ['What is the total joining-fee revenue across the four months?',['₹30,000','₹60,000','₹1,00,000','₹1,20,000'],3,'There are 600 new members, each paying ₹200. Revenue is 600 × ₹200 = ₹1,20,000.']
 ]}
].map(s=>({...s,questions:s.questions.map(([text,options,correct,why])=>({text,options,correct,why}))}));
